name: Ping Backend

# DÃ©clencheurs
on:
  schedule:
    - cron: '*/1 * * * *'  # toutes les 1 minute (UTC)
  workflow_dispatch:         # permet de lancer manuellement

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s ${{ secrets.RENDER_URL }}