name: Ping Backend

# DÃ©clencheurs
on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 5 minutes (UTC)
  workflow_dispatch:         # permet de lancer manuellement

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://keskonmange.onrender.com/ping